---
title: "Create table 1"
author: "Leslie (ZW)"
date: "2024-05-09"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(finalfit)
library(knitr)
```

# Read in the data

```{r,warning=FALSE}
pheno_SOL <- read_csv('~/OneDrive - Beth Israel Lahey Health/2023_methCRP/Data/20240312_pheSol.csv')
ev5 <- read.csv("/Volumes/Sofer Lab/HCHS_SOL/Ancestry_files/UW_GAC_DMDA_20180516_local_ancestries/subject_annotation_2017-09-05.csv")
names(ev5)[2]<-'SOL_ID'
names(ev5)[2]<-'SOL_ID'
pheno_SOL <- merge(pheno_SOL, ev5[,c(2,5:9)],by='SOL_ID')
```

# Create Table 1 (weighted)
```{r}
survey_sol <- svydesign(id=~PSU_ID, strata=~STRAT, weights=~WEIGHT_FINAL_NORM_OVERALL, data=pheno_SOL)
tbl1_var_1<-c("GENDER",'AGE','BMI',"BKGRD1_C7","Age","BMI",'LABA91','SLPA54','SLPA91','SLPA92',
              'SLPA97','ESS','WHIIRS','SLPDUR','DIABETES2_INDICATOR','HYPERTENSION',
              'global_cog_score','global_cog_score_change')

tbl1_weighted <- print(svyCreateTableOne(vars = tbl1_var_1,  data =survey_sol, strata = 'CRP_group'),  varLabels = TRUE,digits =3,pDigits=3, showAllLevels=TRUE)
tb1_noweight<- print(CreateTableOne(vars = tbl1_var_1,data =pheno_SOL, strata = 'CRP_group'),varLabels = TRUE,digits =3,pDigits=3,showAllLevels=TRUE)

tbl1_w <- tbl1_weighted 
tbl1 <- tb1_noweight

tbl1_comb <- tbl1
col_ind_to_update <- which(colnames(tbl1_w) %in% c("Low (<1)", "Borderline (1-3)", "High (>3)"))

# update tbl1_comb with the percentages from the weighted table
for (i in col_ind_to_update){
  counts <- sapply(tbl1[,i], function(x){
                  strsplit(x, split = "(", fixed = TRUE)[[1]][1]
                 })
  percnt <- sapply(tbl1_w[,i], function(x){
                paste0("(",  strsplit(x, split = "(", fixed = TRUE)[[1]][2])
              })
  tbl1_comb[,i] <- paste0(counts, percnt)
}

tbl1_w.overall <- print(svyCreateTableOne(vars = tbl1_var_1,  data =survey_sol),  varLabels = TRUE,digits =3,pDigits=3, showAllLevels=TRUE)
tb1_now.overall<- print(CreateTableOne(vars = tbl1_var_1,data =pheno_SOL),varLabels = TRUE,digits =3,pDigits=3,showAllLevels=TRUE)

tbl1_wo <- tbl1_w.overall
tbl1.nwo <- tb1_now.overall

tbl1_co <- tbl1.nwo
col_ind_to_update <- which(colnames(tbl1_wo) %in% c('Overall'))

# update tbl1_comb with the percentages from the weighted table
for (i in col_ind_to_update){
  counts <- sapply(tbl1.nwo[,i], function(x){
                  strsplit(x, split = "(", fixed = TRUE)[[1]][1]
                 })
  percnt <- sapply(tbl1_wo[,i], function(x){
                paste0("(",  strsplit(x, split = "(", fixed = TRUE)[[1]][2])
              })
  tbl1_co[,i] <- paste0(counts, percnt)
}
tbl1.all <- cbind(tbl1_co,tbl1_comb[,2:4])

#write.csv(tbl1.all, '~/OneDrive - Beth Israel Lahey Health/2023_methCRP/Draft/Tables and Figures/Table1.csv')

# Other way
#results <- survey::svydesign(~ 1, data = tab1, weights = ~ WEIGHT_FINAL_NORM_OVERALL) %>%
#      tbl_svysummary(
#         by = CRP_group,
#         include = c(GENDER,BKGRD1_C7),
#         statistic = list(all_categorical() ~ "{n} ({p}%)")     )
#t=results[[1]]
```


```{r,warning=FALSE}
# unweighted
# Define CRP risk groups and create a variable to get overall summary for the data
pheno_SOL$CRP_group <- as.factor(ifelse(pheno_SOL$LABA91<1, 'Low (<1)', 
                                        ifelse(pheno_SOL$LABA91>3, 'High (>3)', 'Borderline (1-3)')))
pheno_SOL$CRP_group <- relevel(pheno_SOL$CRP_group, ref = 'Low (<1)' )
pheno_SOL$overall<-'Overall'

# Set labels to show in table without changing column names
pheno_SOL$LABA91 <- pheno_SOL$LABA91 %>%
  ff_label("CRP (mg/L)") 
pheno_SOL$GENDER <- pheno_SOL$GENDER %>%
  ff_label("Gender (%)") 
pheno_SOL$AGE <- pheno_SOL$AGE %>%
  ff_label("Age") 
pheno_SOL$HYPERTENSION <- pheno_SOL$HYPERTENSION %>%
  ff_label("Hypertension (%)") 
pheno_SOL$DIABETES2_INDICATOR <- pheno_SOL$DIABETES2_INDICATOR %>%
  ff_label("Diabetes II (%)") 
pheno_SOL$SLPDUR <- pheno_SOL$SLPDUR %>%
  ff_label("Sleep Duration") 
pheno_SOL$SLPA54 <- pheno_SOL$SLPA54 %>%
  ff_label("AHI") 
pheno_SOL$SLPA91 <- pheno_SOL$SLPA91 %>%
  ff_label("Minimum SpO2")  
pheno_SOL$SLPA92 <- pheno_SOL$SLPA92 %>%
  ff_label("Average SpO2") 
pheno_SOL$SLPA97 <- pheno_SOL$SLPA97 %>%
  ff_label("% Time SpO2 <90") 
pheno_SOL$global_cog_score <- pheno_SOL$global_cog_score %>%
  ff_label("Cognitive Baseline") 
pheno_SOL$global_cog_score_change <- pheno_SOL$global_cog_score_change %>%
  ff_label("Cognitive Change") 

# Part of Table 1 with categorical and continuous variables (mean)
Part1 <- c("AGE", "BMI", "GENDER", 'BKGRD1_C7', 'SLPDUR', "HYPERTENSION",
           "DIABETES2_INDICATOR", 'global_cog_score', 'global_cog_score_change')
Tab.P1.1 <- pheno_SOL %>% 
  summary_factorlist("CRP_group", Part1[1:7], na_include=FALSE,cont = "mean", digits = c(1, 1, 3, 1, 0)) %>%
  ff_percent_only() 
Tab.P1.2 <- pheno_SOL %>% 
  summary_factorlist("CRP_group", Part1[8:9], na_include=FALSE,cont = "mean", digits = c(2, 2, 3, 1, 0)) %>%
  ff_percent_only() 
Tab.P1 <- rbind(Tab.P1.1, Tab.P1.2)
# Keep only 1 level for variables with 2 levels
keep <- c(1:3,5:13,15,17,18) 
Tab.P1 <- Tab.P1[keep,]
Tab.P1.overall.1 <- pheno_SOL %>% summary_factorlist('overall', Part1[1:7], na_include=FALSE, 
                                                   cont = "mean", digits = c(1, 1, 3, 1, 0)) %>%
  ff_percent_only()
Tab.P1.overall.2 <- pheno_SOL %>% summary_factorlist('overall', Part1[8:9], na_include=FALSE, 
                                                   cont = "mean", digits = c(2, 2, 3, 1, 0)) %>%
  ff_percent_only()
Tab.P1.overall <- rbind(Tab.P1.overall.1, Tab.P1.overall.2)
Tab.P1.overall <- Tab.P1.overall[keep,]
Tab.P1 <- merge(Tab.P1, Tab.P1.overall, by=c('label','levels'))
# Rearrange the table
Tab.P1 <- Tab.P1[c(7,9,13,8,1:3,5,6,4,15,12,14,10,11), c(1,2,6,3:5)]
# Combine label and level to create a final variable
row.names(Tab.P1) <- 1:nrow(Tab.P1)
Tab.P1$label[4] <- ''
Tab.P1$levels[12:13] <- ''
Tab.P1$Variable[c(1,2,11,14,15)] <- paste0(Tab.P1$label[c(1,2,11,14,15)], ' (', Tab.P1$levels[c(1,2,11,14,15)], ')')
Tab.P1$Variable[3] <- paste0(Tab.P1$label[3], ' - ', Tab.P1$levels[3])
Tab.P1$Variable[4:10] <- paste0(Tab.P1$label[4:10], Tab.P1$levels[4:10])
Tab.P1$Variable[12:13] <- Tab.P1$label[12:13]
Tab.P1 <- Tab.P1[,c(7,3:6)]
kable(Tab.P1)

# Part of Table 1 with continuous variables (median)
Part2 <- c('LABA91', "SLPA54", "SLPA91","SLPA92", 'SLPA97', 'WHIIRS', "ESS")
Tab.P2.1 <- pheno_SOL %>% 
  summary_factorlist("CRP_group", Part2[c(1:4,6,7)], na_include=FALSE, cont = "median") %>%
  ff_percent_only() 
Tab.P2.2 <- pheno_SOL %>% 
  summary_factorlist("CRP_group", Part2[5], na_include=FALSE, cont = "median", 
                     digits = c(2, 2, 3, 1, 0)) %>%
  ff_percent_only() 
Tab.P2 <- rbind(Tab.P2.1, Tab.P2.2)
Tab.P2.overall.1 <- pheno_SOL %>% summary_factorlist('overall', Part2[c(1:4,6,7)], 
                                                     na_include=FALSE, cont = "median") %>%
  ff_percent_only()
Tab.P2.overall.2 <- pheno_SOL %>% summary_factorlist('overall', Part2[5], digits = c(2, 2, 3, 1, 0),
                                                     na_include=FALSE, cont = "median") %>%
  ff_percent_only()
Tab.P2.overall <- rbind(Tab.P2.overall.1, Tab.P2.overall.2)
Tab.P2 <- merge(Tab.P2, Tab.P2.overall, by=c('label','levels'))
# Rearrange the table
Tab.P2 <- Tab.P2[c(4,2,6,3,1,5,7), c(1,2,6,3:5)]
# Combine label and level to create a final variable
row.names(Tab.P2) <- 1:nrow(Tab.P2)
Tab.P2$Variable <- paste0(Tab.P2$label, ' (', Tab.P2$levels, ')')
Tab.P2 <- Tab.P2[,c(7,3:6)]

# Combine part 1 and part 2
Tab.1 <- rbind(Tab.P1, Tab.P2)
group_name <- data.frame(Variable=c('Background (%)', 'Sleep traits', 'Comorbidities', 'Cognitive traits'),
                           Overall=rep(NA,4), Low=rep(NA,4), Borderline=rep(NA,4), High=rep(NA,4) )
names(group_name)[3:5] <- names(Tab.1)[3:5]
Tab.1 <- rbind(Tab.1, group_name)
Tab.1 <- Tab.1[c(1:3,16, 23,4:10, 24,17:22,11, 25,12,13, 26,14,15),]
Tab.1[is.na(Tab.1)] <- ''
Tab.1 <- cbind(Tab.1[,1], do.call(cbind,lapply(Tab.1[2:5], function(x) {gsub(' to', ',',x)})))
names(Tab.1)[1] <- '' 

#write.csv(Tab.1, '~/OneDrive - Beth Israel Lahey Health/2023_methCRP/Draft/Tables and Figures/Table1.csv', row.names = FALSE)
```

